### ISSUE TITLE
csaps-cpp compatibility with MATLAB csaps

### ISSUE THREAD

**Issue by qlahcim** [espdev/csaps-cpp#9]
Is this C++ implementation of CSAPS function compatible with MATLAB built-in implementation CSAPS (https://www.mathworks.com/help/curvefit/csaps.html), at least in the case of univariate signals? I mean especially definition of error/roughness weights and smoothing parameter "p".

![Screenshot from 2024-02-29 14-42-52](https://github.com/espdev/csaps-cpp/assets/2698803/4eab873e-ab99-422b-9681-bf45ddb3ccd0)

**Comment by espdev** [comment]
Hello @michalkvasnicka,

Here is the same formula. Weights are supported, parameter `p` should be in the range [0, 1]. Roughness measure weights via `p`-vector is not implemented.

Otherwise it is the same algorithm (C. de Boor) that works exactly the same way as in MATLAB.
You can also look at [Python implementation](https://github.com/espdev/csaps). It works faster than the MATLAB implementation and requires less memory.
